//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_yeucau.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tech_Support_TicketEntities : DbContext
    {
        public Tech_Support_TicketEntities()
            : base("name=Tech_Support_TicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblchucnang> tblchucnang { get; set; }
        public virtual DbSet<tblkhachhang> tblkhachhang { get; set; }
        public virtual DbSet<tbllichsuthaydoiyeucau> tbllichsuthaydoiyeucau { get; set; }
        public virtual DbSet<tblnguoidung> tblnguoidung { get; set; }
        public virtual DbSet<tblphongban> tblphongban { get; set; }
        public virtual DbSet<tblquyen> tblquyen { get; set; }
        public virtual DbSet<tblyeucauhotrokythuat> tblyeucauhotrokythuat { get; set; }
    }
}
