//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_yeucau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblchucnang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblchucnang()
        {
            this.tblquyen = new HashSet<tblquyen>();
        }
    
        public string ma_chuc_nang { get; set; }
        public string ten_chuc_nang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblquyen> tblquyen { get; set; }
    }
}
