//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QL_yeucau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblphongban
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblphongban()
        {
            this.tblyeucauhotrokythuat = new HashSet<tblyeucauhotrokythuat>();
            this.tblnguoidung = new HashSet<tblnguoidung>();
            this.tblquyen = new HashSet<tblquyen>();
        }
    
        public string ma_phong_ban { get; set; }
        public string ten_phong_ban { get; set; }
        public Nullable<bool> trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblyeucauhotrokythuat> tblyeucauhotrokythuat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblnguoidung> tblnguoidung { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblquyen> tblquyen { get; set; }
    }
}
